### ISSUE TITLE
python main.py ERROR

### ISSUE THREAD

**Issue by Tespera** [chaolongzhang/sinaWeibo#11]
python main.py 后有 ERROR：如下：

```
Traceback (most recent call last):
  File "main.py", line 7, in <module>
    (http, uid) = wblogin()
  File "/www/wwwroot/Tools/Sina/weibo/weibo_login.py", line 67, in wblogin
    login_url = re.search('replace\\(\'([^\']+)\'\\)', resp.text).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by Jing-Scott** [comment]
@chaolongzhang 遇到了同样的问题

**Comment by chaolongzhang** [comment]
这个问题是登录失败造成的，请检查：
1. 登录信息是否正确。
2. 确保登录的时候不需要输入验证码，需要输入验证码时登录会失败。

**Comment by Jing-Scott** [comment]
@chaolongzhang 知道怎么转发微博吗

**Comment by sfdye** [comment]
@chaolongzhang 怎么disable登陆时要输入验证码呢？
