### ISSUE TITLE
下载之后编译运行就报错了

### ISSUE THREAD

**Issue by Eugene1024** [chaolongzhang/sinaWeibo#13]
`:\python\python.exe C:/Users/asus/Desktop/sinaWeibo-master/sinaWeibo-master/main.py
Traceback (most recent call last):
  File "C:/Users/asus/Desktop/sinaWeibo-master/sinaWeibo-master/main.py", line 8, in <module>
    (wei_session, uid) = wblogin()
  File "C:\Users\asus\Desktop\sinaWeibo-master\sinaWeibo-master\weibo\weibo_qrcode.py", line 111, in wblogin
    session = login()
  File "C:\Users\asus\Desktop\sinaWeibo-master\sinaWeibo-master\weibo\weibo_qrcode.py", line 23, in login
    image_name, qrcode_qrid = get_qrcode()
  File "C:\Users\asus\Desktop\sinaWeibo-master\sinaWeibo-master\weibo\weibo_qrcode.py", line 92, in get_qrcode
    qrcode_qrid = re.search(r'"qrid":"(?P<qrid>[\w\-]*)"', qrcode_text).group("qrid")
AttributeError: 'NoneType' object has no attribute 'group'

Process finished with exit code 1`

才学Python不久，看着有点吃力，希望LZ解答下啊

**Comment by dingyang1949** [comment]
一样的错误，暂无头绪

**Comment by beauniverse** [comment]
我也是这个问题，并不会qwq
