### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by dingyang1949** [chaolongzhang/sinaWeibo#15]
C:\Users\Deanlittle\AppData\Local\Programs\Python\Python36\python.exe D:/Demo/work/sinaWeibo-master/main.py
Traceback (most recent call last):
  File "D:/Demo/work/sinaWeibo-master/main.py", line 8, in <module>
    (wei_session, uid) = wblogin()
  File "D:\Demo\work\sinaWeibo-master\weibo\weibo_qrcode.py", line 111, in wblogin
    session = login()
  File "D:\Demo\work\sinaWeibo-master\weibo\weibo_qrcode.py", line 23, in login
    image_name, qrcode_qrid = get_qrcode()
  File "D:\Demo\work\sinaWeibo-master\weibo\weibo_qrcode.py", line 92, in get_qrcode
    qrcode_qrid = re.search(r'"qrid":"(?P<qrid>[\w\-]*)"', qrcode_text).group("qrid")
AttributeError: 'NoneType' object has no attribute 'group'

运行main.py报错

**Comment by rochestertian** [comment]
别用qrcode就好了。用ID登录

**Comment by beauniverse** [comment]
> 别用qrcode就好了。用ID登录

您好！可不可以讲一下具体怎么改呀？我只改了config.py中的login_type还是不行……
